# Generated by Django 5.0.4 on 2024-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
        ('purchase_order_tracking', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_381341_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['quality_rating'], name='purchase_or_quality_b6b268_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['acknowledgment_date'], name='purchase_or_acknowl_8b5ca2_idx'),
        ),
    ]
